### ISSUE TITLE
KT List - Invisible?

### ISSUE THREAD

**Issue by Nand0ze** [SharpWoW/KillTrack#14]
/KT list is not showing up on any char that I have. 

Is this a known issue since the SL Pre-Patch Update? Is there any pending updates for the SL Pre-Patch?

If there is a fix or something I am missing here please let me know!

Thanks
N

**Comment by Sharparam** [comment]
This seems to be due to the changes to how `SetBackdrop` works, I've committed an update that should fix this. It should be available as an alpha download (v1.13.0-1-g5bd2afc) in a bit.

It seems to solve the issue on my end. If you can test it and get back to me that would be great :)

**Comment by Nand0ze** [comment]
Thanks so much for the quick reply!

I am happy to test it if you tell me where and how to download the alpha. 

Also hoping that I don't lose the current kill tracked data in the profile or way to save it so I don't lose it? 👍👍

**Comment by Sharparam** [comment]
You can see the latest versions on CurseForge: https://www.curseforge.com/wow/addons/killtrack/files

You should also be able to update to it in your AddOn client if you set it to look for alpha versions for KillTrack.

Mob data should not be lost, as those are stored in the "WTF" folder separate from the AddOns themselves. It can still be a good idea to keep your "WTF" folder backed up though, you never know what might happen to your system!

**Comment by Nand0ze** [comment]
Thankyou, I will download it and get back to you 👍

**Comment by Nand0ze** [comment]
Just updated - Works perfectly (as of now). Thanks so much!

**Comment by Sharparam** [comment]
Good to hear! I'll make a proper release version then.
