### ISSUE TITLE
WoW Classic Era Update [Version 1.14.4]

### ISSUE THREAD

**Issue by maximus210793** [SharpWoW/KillTrack#24]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game Version of 1.14.4?
Would be awesome, thanks a lot in advance!

**Comment by Sharparam** [comment]
Does it load and function if you select "Load out of date AddOns"? Or are there any Lua errors causing issues on the new patch?

If it's the former I can simply push a version update.

(I don't currently have an active subscription so I don't think I can test on Classic unless there's a PTR for it.)

**Comment by maximus210793** [comment]
Simply pushing a version update would be great :)

**Comment by Sharparam** [comment]
I've pushed v2.31.3 which should be available shortly on all the usual distribution sites. This fixes some issues with kill tracking (#25) and also bumps the interface versions so it should no longer show as out of date.

Thanks for keeping me up to date with things happening in WoW :)
