### ISSUE TITLE
Kill counter seems to be stuck after the latest patch. Sometime around or after when they released 10.2 

### ISSUE THREAD

**Issue by ReysDad** [SharpWoW/KillTrack#25]
## Describe the bug
The kill counter doesn't seem to be advancing recently. I'm tracking mobs/bosses in Mists of Tirna Scithe. Haven't checked other areas

### To Reproduce
Kill any mob I killed previously the counter does not advance.

### Expected behavior
I expect the kill counter to increase by at least 1 after I kill a mob. 

## Environment (please complete the following information)
 - OS: [e.g. Windows 10, Ubuntu 20.04]
 - WoW version/patch: 10.2.0 
 - WoW branch: retail
 - AddOn version:  v2.31.2  
 -  - Are you using a nolibs download of the AddOn? no idea

### Will you be working to fix this problem yourself in a PR? No
Yes/No.

**Comment by Sharparam** [comment]
It seems the data in the CLEU event has changed a bit with how names are formatted, so some of the checks no longer function as they should.

I've pushed a commit that updates the check to work with the new format. I've tested this on PTR to work when solo, but I haven't been able to verify it also works in parties/raids with "count group kills" enabled.

Are you able to test that with the latest alpha version?

Steps to test the group functionality:

 1. Run `/kt countmode` and make sure it says "Now counting kills for every player in the group (party/raid)!", if it says "Now counting your own killing blows ONLY.", simply run it again to toggle it.
 2. Make a raid with someone.
 3. Let the other person kill a mob.
 4. Check that the kill count increments for that mob.

You can download it either from the build artifacts: https://github.com/SharpWoW/KillTrack/suites/18114283983/artifacts/1044176476

Or from CurseForge: https://legacy.curseforge.com/wow/addons/killtrack/files/4861006

(If using the build artifacts link, you need to unzip the zip you get, which itself has two zip files, unzip the one that does *not* have the "nolib" in its name into your AddOns folder.)

**Comment by Sharparam** [comment]
I got confirmation from elsewhere that raid detection should work with the new method, so I think it should be fine to push a new version anyway. Testing of the party/group/raid scenarios would still be appreciated just to make extra sure it still works, if you have the time!

Anyway, v2.31.3 should be available shortly from Curse/WoWI/WAGO and fixes the issue of kills not registering.

**Comment by ReysDad** [comment]
Thanks, it is working fine again for solo. I've been farming Mistcaller solo so I can't really say if it was an issue in groups or not. I don't group often but I'll check the next time I do.
