### ISSUE TITLE
Classic Era Update 1.15.1

### ISSUE THREAD

**Issue by maximus210793** [SharpWoW/KillTrack#28]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.1?
Would be awesome, thanks a lot in advance!

**Comment by Sharparam** [comment]
@maximus210793 Are there any Lua errors in the new game version that need fixing? If not I can just push a simple version bump.

**Comment by maximus210793** [comment]
Just a version bump would be nice :)
Thank you!

**Comment by Sharparam** [comment]
@maximus210793 Interface version has now been updated for retail and vanilla (classic era). v2.31.8 should be available on the AddOn sites shortly :)
