### ISSUE TITLE
WoW Classic Era Update - Version 1.15.2

### ISSUE THREAD

**Issue by maximus210793** [SharpWoW/KillTrack#29]
Hi,
Could you update it to the latest Classic Era Game  Version of 1.15.2?
Would be awesome, thanks a lot in advance!

**Comment by Sharparam** [comment]
It seems the PTR for Classic Era is not currently up. Can you confirm if the AddOn is in a working state on 1.15.2?

**Comment by Sharparam** [comment]
Updates have been pushed to support the latest game clients by now (for Classic Era, that's 1.15.3).
