### ISSUE TITLE
11.0 TWW Pre-Patch Lua Error

### ISSUE THREAD

**Issue by tonydero** [SharpWoW/KillTrack#31]
## Summary
```
`Message: Interface/AddOns/KillTrack/Options.lua:257: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
Time: Thu Jul 25 13:36:53 2024
Count: 1
Stack: Interface/AddOns/KillTrack/Options.lua:257: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)

Locals: 
```
New lua error popping up every time I log in or reload. Looks like `InterfaceOptions_AddCategory` might have seen a change?

1. Install the addon
2. Log in to a character
3. See error

### Expected behavior
No error.

## Environment (please complete the following information)
 - OS: Arch Linux Zen Kernel 6.9.10
 - WoW version/patch:11.0
 - WoW branch: Retail
 - AddOn version: 2.31.8
 - Are you using a nolibs download of the AddOn? No

### Will you be working to fix this problem yourself in a PR?
No

Thanks!

**Comment by Sharparam** [comment]
Sorry for the delay in response!

> Looks like InterfaceOptions_AddCategory might have seen a change?

Yeah, I think it's now been fully removed so AddOns will need to migrate to the new `Settings` API. I'll look at getting it to work with the new stuff (hopefully the PTRs are available).

**Comment by Sharparam** [comment]
And version 2.31.9 should now be available on the usual places with updates to fix the issues!
