### ISSUE TITLE
Suggestion: add count in tooltip

### ISSUE THREAD

**Issue by Barleduq** [SharpWoW/KillTrack#4]
Would it be possible/reasonable to add the count of that mob killed in the hovertext?  I have another addon called Mob Kill Count, that does this. Over all, I like KillTrack better and would like to remove Mob Kill Count, but I *really* like that hovertext shows how many I've killed on current toon / how many overall. 

You mentioned, on wowinterface.com that you would like suggestions and issues put here, and so I am. :D 

-Barleduq on wowI

**Comment by Sharparam** [comment]
This should already be implemented, are you sure it's not there? Try disabling all AddOns and only leave KillTrack enabled, in case it's conflicting with anything. There shouldn't be any conflicts, but who knows.

Also it currently only shows this on mobs that you can attack.

**Comment by Sharparam** [comment]
CLosing this due to lack of response.
