### ISSUE TITLE
Damage over time effects do not count as a kill

### ISSUE THREAD

**Issue by Therrinn** [SharpWoW/KillTrack#5]
When using only dots to kill a target, the kill does not get counted.  This is true even on kills that take more than one tick of the dot or even use multiple dots.

Note: Dots that have an initial damaging effect do count (Shadow Word: Pain and Haunt are examples of this).

**Comment by Sharparam** [comment]
I've added checks for more damage events in the combat log handler, which might resolve this. v2.12.4 is on its way out so if you can try this again with that version and confirm if it works that would be great :)

**Comment by Therrinn** [comment]
Sure, I'll keep an eye out for the update and let you know if it resolves the issue.  Thanks for the quick response!

**Comment by Therrinn** [comment]
Just got the update and it looks like DOT only kills are being tracked properly now.  Thanks for the update!

**Comment by Sharparam** [comment]
Awesome! And thanks for reporting :)
