### ISSUE TITLE
countmode working

### ISSUE THREAD

**Issue by Goten87** [SharpWoW/KillTrack#6]
so im using countmode right now to see the kills i made with my 2 monks
but when my monks hit the same mob it still count as 2 kills instead of 1 i think

is this like how it need to work or is this just me thats being derpy

**Comment by Sharparam** [comment]
One mob dying should only count as one kill. Do you have some more details on where and what mob caused it? And combat logs from around the time of the kill.

**Comment by Goten87** [comment]
im killing the tamed clefhoofs in nagrand(WoD)
im curently not playing anymore so i cant share anything i will add more info when im farming again tomorrow

**Comment by Goten87** [comment]
oke so it is not counting more for party mode but now i have a new issue
when i kill 2 or 3 cleffhoofs at the same time it counts as 1 kill but i kill more

**Comment by Sharparam** [comment]
Hm, can you post some combat log output from such an occasion?

**Comment by Goten87** [comment]
Think its just me it shows correct now
