### ISSUE TITLE
information window

### ISSUE THREAD

**Issue by jackhama91** [SharpWoW/KillTrack#8]
would it be possible to add to add an option for the information window to be displayed on a set position on the screen and not on the cursor like a click and drag window or set it to a corner ?
it can get distracting and in the way on the cursor

**Comment by Sharparam** [comment]
The tooltip that shows up when mousing over the minimap icon or the databroker plugin?

**Comment by jackhama91** [comment]
The one that appears when you put your cursor over a mob

**Comment by Sharparam** [comment]
When mousing over a mob, KillTrack adds information to the default game tooltip. As KillTrack doesn't change anything about where the standard tooltip is displayed, this would need to be configured in whatever AddOn is used to modify it.

(This is a very late reply, I know. At least it's here for future readers now.)
